apiVersion: apps/v1
kind: Deployment
metadata:
  name: journaling-backend
  labels:
    app: journaling-backend
spec:
  replicas: 3  # Start with 3 replicas for high availability
  selector:
    matchLabels:
      app: journaling-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: journaling-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3011"
    spec:
      containers:
      - name: journaling-backend
        image: journaling-backend:latest
        ports:
        - containerPort: 3011
        env:
        - name: PORT
          value: "3011"
        - name: NODE_ENV
          value: "production"
        # Add other environment variables from ConfigMap/Secrets
        envFrom:
        - configMapRef:
            name: journaling-backend-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3011
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3011
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: journaling-backend-service
spec:
  type: LoadBalancer  # or ClusterIP if using an ingress controller
  selector:
    app: journaling-backend
  ports:
  - port: 80
    targetPort: 3011
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: journaling-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: journaling-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 